### PR TITLE
Update Agenda runtime to 23.08

### PR DESCRIPTION
**Pull request by yakushabb**
- Update Agenda runtime to 23.08 since runtime version 21.08 has reached end-of-life.

### CODE REVIEW

**Comment by ghost** [comment]
cleanup part seems not working

```
[📦 com.github.dahenson.agenda app]$ du -h -d 2 .
156K	./include/granite
148K	./include/gee-0.8
408K	./include/vala-0.48
308K	./include/valadoc-0.48
1,0M	./include
484K	./bin
17M	./share/themes
12K	./share/plank
80K	./share/app-info
8,0K	./share/applications
7,9M	./share/vala-0.48
36M	./share/icons
828K	./share/gir-1.0
3,5M	./share/runtime
44K	./share/locale
156K	./share/valadoc-0.48
64K	./share/metainfo
340K	./share/vala
16K	./share/glib-2.0
65M	./share
52K	./lib/pkgconfig
172K	./lib/girepository-1.0
1,4M	./lib/vala-0.48
4,0K	./lib/debug
268K	./lib/valadoc-0.48
1,1M	./lib/graphviz
11M	./lib
77M
```

**Comment by ghost** [comment]
@hfiguiere Could you review changes related to Agenda? Thanks.

**Comment by ghost** [comment]
@bbhtt I've updated Agenda runtime to 23.08

**Comment by bbhtt** [comment]
bot, build

**Pull request merged**
